//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int IDOrder { get; set; }
        public Nullable<int> IDCus { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public string AddressDelivery { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string PaymentMethod { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
