//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int IDDetail { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> IDSize { get; set; }
        public Nullable<int> IDColor { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductColor ProductColor { get; set; }
        public virtual ProductSize ProductSize { get; set; }
    }
}
