//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        public int IDVariant { get; set; }
        public int IDProduct { get; set; }
        public int IDSize { get; set; }
        public int IDColor { get; set; }
        public int Quantity { get; set; }
    
        public virtual ProductColor ProductColor { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductSize ProductSize { get; set; }
    }
}
